// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseBooksDir():Promise<string>;

export function GetHostStatus():Promise<main.HostStatus>;

export function GetSession():Promise<main.SessionInfo>;

export function Log(arg1:string):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function Logout():Promise<void>;

export function ScanBooks(arg1:string):Promise<Array<main.BookInfo>>;

export function SendEmailCode(arg1:string):Promise<void>;

export function SetBooksDir(arg1:string):Promise<void>;

export function StartHost():Promise<main.HostStatus>;

export function StopHost():Promise<void>;
