// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseBooksDir() {
  return window['go']['main']['App']['ChooseBooksDir']();
}

export function GetHostStatus() {
  return window['go']['main']['App']['GetHostStatus']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function ScanBooks(arg1) {
  return window['go']['main']['App']['ScanBooks'](arg1);
}

export function SendEmailCode(arg1) {
  return window['go']['main']['App']['SendEmailCode'](arg1);
}

export function SetBooksDir(arg1) {
  return window['go']['main']['App']['SetBooksDir'](arg1);
}

export function StartHost() {
  return window['go']['main']['App']['StartHost']();
}

export function StopHost() {
  return window['go']['main']['App']['StopHost']();
}
